server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: demo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: koi.mjsong@gmail.com
    password: onmw dzuu rxch ynpk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 18000000
    redis:
      host: localhost
      port: 6379
      timeout: 5000
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect


token:
  expiration:
    access: 30000       # AccessToken 유효기간 30초 (밀리초)
    refresh: 300000     # RefreshToken 유효기간 5분 (밀리초)

cookie:
  secure: false # 운영 환경에서는 true, 개발 환경에서는 false